# How to reset user:
# sudo -u postgres psql
# *admin password*
# DROP DATABASE 'weafam_development";
# DROP USER weafam_admin;
# /q
# sudo -u postgres createuser -P
# weafam_admin
# password for it
# rake db:setup
development:  # my version
  adapter: postgresql
  database: weafam_development
  username: weafam_admin
  password: gR0v1Ng3i
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: UTF8
  database: weafam_test
  username: weafam_admin
  password: gR0v1Ng3i
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: UTF8
  database: weafam_production
  pool: 5
  username: weafam_admin
  password: gR0v1Ng3i
  timeout: 5000
