require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UpdateFeedsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # UpdateFeed. As you add validations to UpdateFeed, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UpdateFeedsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all updates_feeds as @updates_feeds" do
      update_feed = UpdateFeed.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:updates_feeds)).to eq([update_feed])
    end
  end

  describe "GET show" do
    it "assigns the requested update_feed as @update_feed" do
      update_feed = UpdateFeed.create! valid_attributes
      get :show, {:id => update_feed.to_param}, valid_session
      expect(assigns(:update_feed)).to eq(update_feed)
    end
  end

  describe "GET new" do
    it "assigns a new update_feed as @update_feed" do
      get :new, {}, valid_session
      expect(assigns(:update_feed)).to be_a_new(UpdateFeed)
    end
  end

  describe "GET edit" do
    it "assigns the requested update_feed as @update_feed" do
      update_feed = UpdateFeed.create! valid_attributes
      get :edit, {:id => update_feed.to_param}, valid_session
      expect(assigns(:update_feed)).to eq(update_feed)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UpdateFeed" do
        expect {
          post :create, {:update_feed => valid_attributes}, valid_session
        }.to change(UpdateFeed, :count).by(1)
      end

      it "assigns a newly created update_feed as @update_feed" do
        post :create, {:update_feed => valid_attributes}, valid_session
        expect(assigns(:update_feed)).to be_a(UpdateFeed)
        expect(assigns(:update_feed)).to be_persisted
      end

      it "redirects to the created update_feed" do
        post :create, {:update_feed => valid_attributes}, valid_session
        expect(response).to redirect_to(UpdateFeed.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved update_feed as @update_feed" do
        post :create, {:update_feed => invalid_attributes}, valid_session
        expect(assigns(:update_feed)).to be_a_new(UpdateFeed)
      end

      it "re-renders the 'new' template" do
        post :create, {:update_feed => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested update_feed" do
        update_feed = UpdateFeed.create! valid_attributes
        put :update, {:id => update_feed.to_param, :update_feed => new_attributes}, valid_session
        update_feed.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested update_feed as @update_feed" do
        update_feed = UpdateFeed.create! valid_attributes
        put :update, {:id => update_feed.to_param, :update_feed => valid_attributes}, valid_session
        expect(assigns(:update_feed)).to eq(update_feed)
      end

      it "redirects to the update_feed" do
        update_feed = UpdateFeed.create! valid_attributes
        put :update, {:id => update_feed.to_param, :update_feed => valid_attributes}, valid_session
        expect(response).to redirect_to(update_feed)
      end
    end

    describe "with invalid params" do
      it "assigns the update_feed as @update_feed" do
        update_feed = UpdateFeed.create! valid_attributes
        put :update, {:id => update_feed.to_param, :update_feed => invalid_attributes}, valid_session
        expect(assigns(:update_feed)).to eq(update_feed)
      end

      it "re-renders the 'edit' template" do
        update_feed = UpdateFeed.create! valid_attributes
        put :update, {:id => update_feed.to_param, :update_feed => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested update_feed" do
      update_feed = UpdateFeed.create! valid_attributes
      expect {
        delete :destroy, {:id => update_feed.to_param}, valid_session
      }.to change(UpdateFeed, :count).by(-1)
    end

    it "redirects to the updates_feeds list" do
      update_feed = UpdateFeed.create! valid_attributes
      delete :destroy, {:id => update_feed.to_param}, valid_session
      expect(response).to redirect_to(update_feeds_url)
    end
  end

end
